### PR TITLE
Angular 14

### PR DESCRIPTION
**Pull request by andreas-fahrecker**
Since a Project I work on got updated to Angular 14, which is/was dependent on ngx-joystick, I updated the library to Angular 14.

I also already updated the README.md files just like it was suggested in the pull request for the Angular 12 update.

### CODE REVIEW

**Comment by wweitzel** [comment]
Cool! I will take a look this weekend. Thanks

**Comment by andreas-fahrecker** [comment]
I have just noticed that the updated version of nippleJs can behave buggy, when the parent element of the joystick has the css value display: block.

So it might be better to create a version with just the updated angular version with just nippleJs 0.9.0 and one with 0.9.1

**Comment by wweitzel** [comment]
@andreas-fahrecker I'm getting when trying to build this
```
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(extractCss).
```

Steps to reproduce
1. Checkout this branch
2. Run npm install
3. run ```ng build ngx-joystick``` to build the library
4. run ```ng build -c production``` to build the demo app

Step 4 has the above error. Seems like we need to remove the `extractCss` from `angular.json`

**Comment by wweitzel** [comment]
Closing this since I could not get it to build. And Angular 14 is now done https://github.com/wweitzel/ngx-joystick/pull/13

**Pull request closed without merging**
